### ISSUE TITLE
Create API (Interface) for logging

### ISSUE THREAD

**Issue by Mikado3780** [Kros-sk/Kros.Libs#13]
- In Kros.Utils will be only interface without implementation. Those implementations will be in separate libraries.

API should satisfy:
- Has to be compatible with logging in .NET Core.
- Use extisting system (Serilog, NLog...). 
- Logging in code is persistent. Whether the log is saved (or written) is defined by configuration.
- Logging is modified via configuration, out of application, without precompiling code.
- Logging should be as fast as possible. If logs are written somewhere, slowing is expected.

**Comment by satano** [comment]
We will not do this one.
