### ISSUE TITLE
Fluent SQL DDL statements

### ISSUE THREAD

**Issue by Mikado3780** [Kros-sk/Kros.Libs#15]
DDL should contains:
- `CREATE TABLE` : Columns, Primary Key, Indexes, Foreign keys.
- `DROP TABLE`
- `ALTER TABLE` : Add/Delete/Modify/Rename columns.
- `CREATE INDEX` : Type, Columns, Clustered
- `DROP INDEX`
- `CREATE FOREIGN KEY` : Columns, Delete/Update rule.
- `DROP FOREIGN KEY`

- Executing will be on demand, like as Linq.

**Comment by satano** [comment]
Rejected.
